# Generated by Django 5.1.7 on 2025-04-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas internas para administradores', null=True),
        ),
    ]
